from pages.About_Us import about_page
from pages.Tutorials import tutorials_page
from pages.Glossary import glossary_page
from pages.Home_Page import home_page
from pages.Meta_Data import meta_data_page
from pages.Search import search_page
from pages.Citations import citations_page
from pages.Login import login_page
from pages.gene_info import gene_info_page
from pages.mirna import mirna_info_page
from pages.rna_type import rna_type_page
from pages.spatial_expression import spatial_info_page
from pages.ppi_interaction import ppi_info_page
from pages.go_kegg import go_info_page
from pages.localisation import local_info_page
from pages.Orthologs import orthologs_info_page
from pages.snp_info import snp_info_page